name: corpo_ui_example
description: Example app demonstrating Corpo UI components and features.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  corpo_ui:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
