name: corpo_ui
description: "A comprehensive Flutter design system with corporate-focused UI components, themes, and utilities inspired by Shadcn UI principles."
version: 0.1.0
homepage: https://github.com/sazardev/corpo_ui
repository: https://github.com/sazardev/corpo_ui
issue_tracker: https://github.com/sazardev/corpo_ui/issues
documentation: https://github.com/sazardev/corpo_ui#readme

topics:
  - ui
  - design-system
  - flutter-package
  - corporate
  - components
  - theme
  - material-design

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter: